export function exportToCSV(
  headers: string[],
  rows: (string | number)[][],
  filename = 'consultara-export.csv',
): void {
  const esc = (v: string | number) => {
    const s = String(v ?? '');
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const csv = [headers, ...rows].map(row => row.map(esc).join(',')).join('\n');
  const blob = new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function printCurrentPage(): void {
  window.print();
}

export function downloadMockReport(name: string, ext = 'pdf'): void {
  // Stub — in production this POSTs to /api/export and streams the file
  const anchor = document.createElement('a');
  anchor.href = '#';
  anchor.title = `${name}.${ext}`;
  // Create a tiny text blob as placeholder content
  const blob = new Blob(
    [`${name}\nGenerated by Consultara Global — ${new Date().toLocaleString('en-IN')}\n`],
    { type: ext === 'pdf' ? 'application/pdf' : 'application/vnd.ms-excel' },
  );
  anchor.href = URL.createObjectURL(blob);
  anchor.download = `${name.replace(/\s+/g, '_')}.${ext}`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  setTimeout(() => URL.revokeObjectURL(anchor.href), 1000);
}
